build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN"

test-job:
  stage: test
  script:
    - echo "This job test something"

test-job2:
  stage: test
  script:
    - echo "This job test something2"

deploy-prod:
  stage: deploy
  script:
    - echo "This is deploy $CI_COMMIT_BRANCH"
